POST http://localhost:4000/add

Content-Type: application/json

{
    "text": "Ekmek almaya git!"
}

Bir satir altda ki üc tane sembol üsttekileri alttakilerden ayirmak icin kullaniliyor.
###


GET http://localhost:4000/todos

###


DELETE http://localhost:4000/deleteToto/0.0020351572540928675


###

POST http://localhost:4000/toggleTodo/0.6753051232298888